// vue/my-back-system/src/views/Home/index.vue
<template>
    <div>
        <el-row>
            <el-col :span="8" style="padding-right:10px">
                <el-card class="box-card">
                    <div class="user">
                        <img src="@/assets/images/user.jpg" alt="">
                        <div class="userinfo">
                            <p class="name">Admin</p>
                            <p class="access">超级管理员</p>
                        </div>
                    </div>
                    <div class="login-info">
                        <p>上次登录时间：<span>2022-10-10</span></p>
                        <p>上次登录地点：<span>武汉</span></p>
                    </div>
                </el-card>
                <el-card style="margin-top: 20px;height: 343px;">
                    <el-table :data="tableData" stripe style="width: 100%">
                        <el-table-column v-for="(value, key) in tableLabel" :prop="key" :label="value" :key="value" />
                    </el-table>
                </el-card>
            </el-col>
            <el-col :span="16" style="padding-left:10px">
                <div class="num">
                    <el-card v-for="item in countData" :key="item.name" :body-style="{ display: 'flex', padding: 0 }">
                        <el-icon class="icon" :style="{ backgroundColor: item.color }">
                            <component :is='item.icon' />
                        </el-icon>
                        <div class="detail">
                            <p class="price">￥{{ item.value }}</p>
                            <p class="desc">{{ item.name }}</p>
                        </div>
                    </el-card>
                </div>
                <el-card style="height: 226px;">
                    <div ref="echarts1" style="height: 236px;"></div>
                </el-card>
                <div class="graph">
                    <el-card style="height: 220px;">
                        <div ref="echarts2" style="height: 236px;"></div>
                    </el-card>
                    <el-card style="height: 220px;">
                        <div ref="echarts3" style="height: 200px;"></div>
                    </el-card>
                </div>
            </el-col>
        </el-row>
    </div>
</template>

<script setup>
import { nextTick, onMounted, ref } from 'vue'
import { getData } from '@/api';
import * as echarts from 'echarts'

let echarts1 = ref(null)
let echarts2 = ref(null)
let echarts3 = ref(null)

onMounted(async () => {
    const data = await getData()//拿到数据
    // console.log(data.data.data.orderData[0].data[0]);
    tableData.value = data.data.data.tableData
    tableLabel.value = data.data.data.tableLabel
    countData.value = data.data.data.countData

    nextTick(() => {//拿到dom

        //折线图
        let echartsOne = echarts.init(echarts1.value)
        let order = data.data.data.lineData[0]
        // console.log(order.data);
        let xData = order.date
        let optionOne = {
            legend: {
                data: Object.keys(order.data[0])
            },
            tooltip: {
                trigger: 'item'
            },
            xAxis: {
                data: xData
            },
            yAxis: {
                type: 'value'
            },
            series: []
        }
        Object.keys(order.data[0]).forEach(key => {
            optionOne.series.push({
                name: key,
                type: 'line',
                data: order.data.map(item => item[key])
            })
        })
        // console.log(optionOne.series);
        echartsOne.setOption(optionOne)


        //柱状图
        let echartsTwo = echarts.init(echarts2.value)
        let optionTwo = {
            legend:{
                textStyle:{
                    color: '#333'
                }
            },
            grid:{
                left:'20%'
            },
            tooltip: {
                trigger: 'axis'
            },
            xAxis: {
                type: 'category',
                data: data.data.data.userData.map(item => item.date),
                axisLine: {
                    lineStyle: {
                        color: '#17b3a3'
                    }
                },
                axisLabel: {
                    interval: 0,
                    color: '#333'
                }
            },
            yAxis: {
                type: 'value',
                axisLine: {
                    lineStyle: {
                        color: '#17b3a3'
                    }
                }
            },
            color:['#2ec7c9','#b6a2de'],
            series: [
                {
                    name: '新增用户',
                    type: 'bar',
                    data: data.data.data.userData.map(item => item.new),
                    
                },
                {
                    name: '活跃用户',
                    type: 'bar',
                    data: data.data.data.userData.map(item => item.active)
                }
            ]
        }
        echartsTwo.setOption(optionTwo)

        //饼状图
        let echartsThree = echarts.init(echarts3.value)
        let optionThree = {
            tooltip: {
                trigger: 'item'
            },
            color: [
                '#0f78f4',
                '#dd536b',
                '#9462e5',
                '#a6a6a6',
                '#e1bb22',
                '#39c363',
                '#3ed1cf'
            ],
            series: [
                {
                    data: data.data.data.videoData,
                    type: 'pie'
                }
            ]
        }
        echartsThree.setOption(optionThree)

    })
})


const tableData = ref([])

const tableLabel = ref({})

const countData = ref([])
</script>

<style lang="less" scoped>
.user {
    display: flex;
    align-items: center;
    padding-bottom: 20px;
    margin-bottom: 20px;
    border-bottom: 1px solid #ccc;

    img {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        margin-right: 40px;
    }

    .userinfo {
        .name {
            font-size: 32px;
            margin-bottom: 10px;
        }

        .access {
            color: #999999;
        }
    }
}

.login-info {
    p {
        line-height: 28px;
        font-size: 14px;
        color: #999999;

        span {
            color: #666666;
            margin-left: 60px;
        }
    }
}

.num {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;

    .el-card__body {
        padding: 0 !important;
    }

    .icon {
        width: 70px;
        height: 70px;
        font-size: 30px;
        text-align: center;
        line-height: 80px;
        color: #fff;
    }

    .detail {
        display: flex;
        flex-direction: column;
        justify-content: center;
        margin-left: 20px;

        .price {
            font-size: 28px;
            margin-bottom: 10px;
            line-height: 30px;
            height: 30px;
        }

        .desc {
            font-size: 14px;
            color: #999;
            text-align: center;
        }
    }

    .el-card {
        width: 32%;
        margin-bottom: 20px;
    }
}

.graph {
    display: flex;
    justify-content: space-between;
    margin-top: 20px;

    .el-card {
        width: 48%;
    }
}
</style>

// React/my-back-system-react/src/pages/Home/index.tsx
import React, { useEffect, useState } from 'react';
import { Row, Col, Card, Table } from 'antd';
import './index.css';
import userImg from '@/assets/images/avatar.jpg';
import { getData } from '@/api';
import { columns } from './data';
import { icon2Element } from '@/utils/icon';
import Echarts from '@/components/Echarts';

const Home: React.FC = () => {
    const [tableData, setTableData] = useState<tableType[]>([]);
    const [countData, setCountData] = useState<countType[]>([]);
    const [echartsData, setEchartsData] = useState<dataType>({} as dataType);

    useEffect(() => {
        getData().then(({ data }) => {
            const { tableData, orderData, userData, videoData, countData } =
                data;
            setTableData(tableData as tableType[]);
            setCountData(countData as countType[]);

            //获取折线图数据
            const order = orderData;
            const xData = order.date;
            if (!order.data) return;
            const keyArray = Object.keys(order.data[0]);
            const series: seriesType[] = [] as unknown as seriesType[];
            keyArray.forEach((key) => {
                if (!order.data) return;
                series.push({
                    name: key,
                    data: order.data.map((item) => item[key]),
                    type: 'line',
                });
            });
            setEchartsData({
                data: {
                    orderData: {
                        xData,
                        series,
                    },
                    userData: {
                        xData: (userData as userType[]).map(
                            (item) => item.date,
                        ) as string[],
                        series: [
                            {
                                name: '新增用户',
                                data: (userData as userType[]).map(
                                    (item) => item.new,
                                ) as number[],
                                type: 'bar',
                            },
                            {
                                name: '活跃用户',
                                data: (userData as userType[]).map(
                                    (item) => item.active,
                                ) as number[],
                                type: 'bar',
                            },
                        ],
                    },
                    videoData: {
                        series: [
                            {
                                data: videoData as number[],
                                type: 'pie',
                            },
                        ],
                    },
                },
            });
        });
    }, []);
    return (
        <Row className="home">
            <Col span={8}>
                <Card hoverable>
                    <div className="user">
                        <img src={userImg} alt="user" />
                        <div className="userinfo">
                            <p className="name">Admin</p>
                            <p className="access">超级管理员</p>
                        </div>
                    </div>
                    <div className="login-info">
                        <p className="login-time">
                            上次登录时间：<span>2024-6-1</span>
                        </p>
                        <p className="login-ip">
                            上次登录地点：<span>北京</span>
                        </p>
                    </div>
                </Card>
                <Card>
                    <Table
                        columns={columns}
                        dataSource={tableData}
                        pagination={false}
                        rowKey={(record) => record.name as string}
                    ></Table>
                </Card>
            </Col>
            <Col span={16}>
                <div className="num">
                    {countData.map((item) => (
                        <Card key={item.name}>
                            <div
                                className="icon-box"
                                style={{ backgroundColor: item.color }}
                            >
                                {icon2Element(item.icon)}
                            </div>
                            <div className="detail">
                                <p className="num">￥{item.value}</p>
                                <p className="txt">{item.name}</p>
                            </div>
                        </Card>
                    ))}
                </div>
                {echartsData.data?.orderData && (
                    <Echarts
                        chartData={echartsData.data.orderData as ChartData}
                        style={{ height: '280px', marginTop: '30px' }}
                    ></Echarts>
                )}
                <div className="graph">
                    {echartsData.data?.userData && (
                        <Echarts
                            chartData={
                                echartsData.data
                                    .userData as unknown as ChartData
                            }
                            style={{
                                height: '240px',
                                width: '50%',
                                marginLeft: '20px',
                            }}
                        ></Echarts>
                    )}
                    {echartsData.data?.videoData && (
                        <Echarts
                            chartData={
                                echartsData.data
                                    .videoData as unknown as ChartData
                            }
                            style={{ height: '240px', width: '50%' }}
                        ></Echarts>
                    )}
                </div>
            </Col>
        </Row>
    );
};

export default Home;
