// React/my-back-system-react/src/pages/Login/index.tsx
import React from 'react';
import './index.css';
import { Form, Input, Button, message } from 'antd';
import { getMenu } from '@/api';
import { useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { setMenuList } from '@/store/reducers/tabs';

const View: React.FC = () => {
    const dispatch = useDispatch();
    const navigate = useNavigate();
    const [messageApi, contextHolder] = message.useMessage();
    const handleSubmit = (values: { username: string; password: string }) => {
        getMenu(values)
            .then((res) => {
                if (res.code === 20000) {
                    messageApi.open({
                        type: 'success',
                        content: '登录成功',
                    });
                    navigate('/home');
                    dispatch(setMenuList(res.data.menu));
                    localStorage.setItem(
                        'token',
                        JSON.stringify(res.data.token),
                    );
                } else if (res.code === -999) {
                    messageApi.open({
                        type: 'error',
                        content: res.data.message,
                    });
                }
            })
            .catch((res) => {
                messageApi.open({
                    type: 'error',
                    content: res.data.message,
                });
            });
    };
    return (
        <Form className="login-container" onFinish={handleSubmit}>
            {contextHolder}
            <div className="login-title">登录</div>
            <Form.Item
                label="账号"
                name="username"
                rules={[{ required: true, message: '请输入账号' }]}
            >
                <Input defaultValue="admin" placeholder="账号" />
            </Form.Item>
            <Form.Item
                name="password"
                label="密码"
                rules={[{ required: true, message: '请输入密码' }]}
            >
                <Input.Password defaultValue="admin" placeholder="密码" />
            </Form.Item>
            <Form.Item className="login-button">
                <Button type="primary" htmlType="submit">
                    登录
                </Button>
            </Form.Item>
        </Form>
    );
};

export default View;

// vue/my-back-system/src/views/Login/index.vue
<template>
    <div class="login-container">
        <el-form label-width="70px" :model="form" :rules="rules" :inline="true" ref="loginForm">
            <div class="login-title">
                <h2 style="margin-bottom: 20px;">登录</h2>
            </div>
            <el-form-item label="用户名" prop="username">
                <el-input v-model="form.username" placeholder="请输入用户名" />
            </el-form-item>
            <el-form-item label="密码" prop="password">
                <el-input v-model="form.password" type="password" placeholder="请输入密码" />
            </el-form-item>
            <el-form-item>
                <el-button style="margin:10px 0 10px 105px;" type="primary" @click="handleLogin">登录</el-button>
            </el-form-item>
        </el-form>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { getMenu } from '@/api'
import { useRouter } from 'vue-router'
import { useStore } from '@/store';

const router = useRouter();
const loginForm = ref(null);
const store = useStore();

const form = ref({
    username: 'admin',
    password: '123456'
});

const rules = ref({
    username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
    password: [{ required: true, message: '请输入密码', trigger: 'blur' }]
});

const handleLogin = () => {
    loginForm.value.validate((valid) => {
        if (valid) {
            getMenu(form.value).then(res => {
                console.log(res);
                if (res.data.code === 20000) {
                    store.getMenuList(res.data.data.menu)
                    // console.log(router);
                    store.addRouter(router)
                    localStorage.setItem('token', res.data.data.token)
                    router.push('/home')
                    ElMessage({
                        message: res.data.data.message,
                        type: 'success',
                    })
                } else if (res.data.code === -999) {
                    ElMessage({
                        message: res.data.data.message,
                        type: 'error',
                    })
                }
            })
        }
    })
}
</script>

<style lang="less" scoped>
.login-container {
    width: 350px;
    border: 1px solid #eaeaea;
    padding: 35px 35px 15px 35px;
    background-color: #fff;
    border-radius: 15px;
    box-shadow: 0 0 25px #cac6c6;
    margin: 180px auto;
    box-sizing: border-box;

    .login-title {
        text-align: center;
        margin-bottom: 35px;
    }

    .el-input {
        width: 200px;
    }
}
</style>
