// 面试题/token/client/src/views/Login.vue
<template>
    <div>
        <van-form @submit="onSubmit">
            <van-cell-group inset>
                <van-field v-model="username" name="username" label="用户名" placeholder="用户名"
                    :rules="[{ required: true, message: '请填写用户名' }]" />
                <van-field v-model="password" type="password" name="password" label="密码" placeholder="密码"
                    :rules="[{ required: true, message: '请填写密码' }]" />
            </van-cell-group>
            <div style="margin: 16px;">
                <van-button round block type="primary" native-type="submit">
                    登录
                </van-button>
            </div>
        </van-form>

    </div>
</template>

<script setup>
import { ref } from "vue";
import { login } from "../api/user.js";
import { useRouter } from "vue-router";

const router = useRouter()

const username = ref('')
const password = ref('')

const onSubmit=(values)=>{
    console.log(values);
    // axios.post('http://localhost:3000/login',values).then((res)=>{
    //     console.log(res);//后端返回的结果
    //     localStorage.setItem('token',res.data.token);
    //     router.push('/home')
    // })
    login(values).then((res)=>{
        console.log(res);
        localStorage.setItem('token',res.token);
        router.push('/home')
        // window.location.href = '/home'//原生js跳首页，触发浏览器刷新
    })
}
</script>

<style lang="css" scoped></style>

// React/my-back-system-react/src/pages/Login/index.tsx
import React from 'react';
import './index.css';
import { Form, Input, Button, message } from 'antd';
import { getMenu } from '@/api';
import { useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { setMenuList } from '@/store/reducers/tabs';

const View: React.FC = () => {
    const dispatch = useDispatch();
    const navigate = useNavigate();
    const [messageApi, contextHolder] = message.useMessage();
    const handleSubmit = (values: { username: string; password: string }) => {
        getMenu(values)
            .then((res) => {
                if (res.code === 20000) {
                    messageApi.open({
                        type: 'success',
                        content: '登录成功',
                    });
                    navigate('/home');
                    dispatch(setMenuList(res.data.menu));
                    localStorage.setItem(
                        'my-back-token',
                        JSON.stringify(res.data.token),
                    );
                } else if (res.code === -999) {
                    messageApi.open({
                        type: 'error',
                        content: res.data.message,
                    });
                }
            })
            .catch((res) => {
                messageApi.open({
                    type: 'error',
                    content: res.data.message,
                });
            });
    };
    return (
        <Form className="login-container" onFinish={handleSubmit}>
            {contextHolder}
            <div className="login-title">登录</div>
            <Form.Item
                label="账号"
                name="username"
                rules={[{ required: true, message: '请输入账号' }]}
            >
                <Input placeholder="账号" />
            </Form.Item>
            <Form.Item
                name="password"
                label="密码"
                rules={[{ required: true, message: '请输入密码' }]}
            >
                <Input.Password placeholder="密码" />
            </Form.Item>
            <Form.Item className="login-button">
                <Button type="primary" htmlType="submit">
                    登录
                </Button>
            </Form.Item>
        </Form>
    );
};

export default View;
