// React/react-demo/src/pages/login/index.jsx
import { Button, Form, Input } from 'antd';
import './index.css';
import { useNavigate } from 'react-router-dom';

const Login = () => {
  const navigate = useNavigate();


  const onFinish = (values) => {
    console.log(values);
    navigate('/layout');
  };
  const onFinishFailed = (errorInfo) => {
    console.log(errorInfo);
  };
  return (
    <div className='login'>
      <Form
        name="basic"
        labelCol={{
          span: 4,
        }}
        wrapperCol={{
          span: 20,
        }}
        style={{
          maxWidth: 600,
        }}
        initialValues={{
          remember: true,
        }}
        onFinish={onFinish}
        onFinishFailed={onFinishFailed}
        autoComplete="off"
      >
        <Form.Item
          label="用户名"
          name="username"
          rules={[
            {
              required: true,
              message: '请输入用户名!',
            },
          ]}
        >
          <Input />
        </Form.Item>

        <Form.Item
          label="密码"
          name="password"
          rules={[
            {
              required: true,
              message: '请输入密码!',
            },
          ]}
        >
          <Input.Password />
        </Form.Item>
        <Form.Item
          wrapperCol={{
            offset: 0,
            span: 24,
          }}
        >
          <Button type="primary" htmlType="submit">
            登录
          </Button>
        </Form.Item>
      </Form>
    </div>
  )
};
export default Login;

// 面试题/token/client/src/views/Login.vue
<template>
    <div>
        <van-form @submit="onSubmit">
            <van-cell-group inset>
                <van-field v-model="username" name="username" label="用户名" placeholder="用户名"
                    :rules="[{ required: true, message: '请填写用户名' }]" />
                <van-field v-model="password" type="password" name="password" label="密码" placeholder="密码"
                    :rules="[{ required: true, message: '请填写密码' }]" />
            </van-cell-group>
            <div style="margin: 16px;">
                <van-button round block type="primary" native-type="submit">
                    登录
                </van-button>
            </div>
        </van-form>

    </div>
</template>

<script setup>
import { ref } from "vue";
import { login } from "../api/user.js";
import { useRouter } from "vue-router";

const router = useRouter()

const username = ref('')
const password = ref('')

const onSubmit=(values)=>{
    console.log(values);
    // axios.post('http://localhost:3000/login',values).then((res)=>{
    //     console.log(res);//后端返回的结果
    //     localStorage.setItem('token',res.data.token);
    //     router.push('/home')
    // })
    login(values).then((res)=>{
        console.log(res);
        localStorage.setItem('token',res.token);
        router.push('/home')
        // window.location.href = '/home'//原生js跳首页，触发浏览器刷新
    })
}
</script>

<style lang="css" scoped></style>
